/**
 * OG Image component for blog articles.
 *
 * Called from: src/app/blog/<slug>/opengraph-image.tsx (generated by engine)
 *
 * Engine generates files like this:
 *   import { BlogOGImage } from "@/components/seo/BlogOGImage";
 *   export const dynamic = "force-static";
 *   export const alt = "Article title";
 *   export const size = { width: 1200, height: 630 };
 *   export const contentType = "image/png";
 *   export default async function Image() {
 *     return BlogOGImage({ title: "...", category: "Guide", subtitle: "..." });
 *   }
 *
 * TODO: Customize brand colors, logo initials, and site name/URL below.
 * Search for "TODO" to find all customization points.
 */

import { ImageResponse } from "next/og";

export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

interface BlogOGImageProps {
  title: string;
  category?: string;
  subtitle?: string;
}

export function BlogOGImage({ title, category = "Blog", subtitle }: BlogOGImageProps) {
  // TODO: Replace these with your brand colors
  const brandPrimary = "#3b82f6";       // matches --primary in theme-dark
  const brandBackground = "#0d0d0d";
  const brandSecondary = "#1a1a2e";

  // TODO: Replace "MB" with your brand initials
  const brandInitials = "MB";

  // TODO: Replace "My Blog" and "myblog.com/blog" with your real values
  const brandName = "My Blog";
  const brandUrl = "myblog.com/blog";

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
          justifyContent: "space-between",
          background: `linear-gradient(135deg, ${brandBackground} 0%, ${brandSecondary} 50%, ${brandBackground} 100%)`,
          fontFamily: "system-ui, -apple-system, sans-serif",
          padding: "60px 80px",
          position: "relative",
        }}
      >
        {/* Subtle grid overlay */}
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundImage: `
              linear-gradient(rgba(59, 130, 246, 0.03) 1px, transparent 1px),
              linear-gradient(90deg, rgba(59, 130, 246, 0.03) 1px, transparent 1px)
            `,
            backgroundSize: "60px 60px",
          }}
        />

        {/* Glow effects */}
        <div
          style={{
            position: "absolute",
            top: "20%",
            left: "10%",
            width: 400,
            height: 400,
            background: `radial-gradient(circle, ${brandPrimary}26 0%, transparent 70%)`,
            filter: "blur(60px)",
          }}
        />
        <div
          style={{
            position: "absolute",
            bottom: "20%",
            right: "10%",
            width: 300,
            height: 300,
            background: `radial-gradient(circle, ${brandPrimary}1a 0%, transparent 70%)`,
            filter: "blur(60px)",
          }}
        />

        {/* Main content */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "flex-start",
            zIndex: 1,
            flex: 1,
            justifyContent: "center",
          }}
        >
          {/* Category badge */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              padding: "10px 24px",
              background: `${brandPrimary}1a`,
              border: `1px solid ${brandPrimary}4d`,
              borderRadius: 24,
              marginBottom: 32,
            }}
          >
            <span style={{ fontSize: 20, color: brandPrimary, fontWeight: 600 }}>
              {category}
            </span>
          </div>

          {/* Title */}
          <div style={{ display: "flex", flexDirection: "column", maxWidth: 1000 }}>
            <span
              style={{
                fontSize: title.length > 60 ? 52 : 64,
                fontWeight: 700,
                color: "#ffffff",
                lineHeight: 1.1,
                marginBottom: subtitle ? 24 : 0,
                letterSpacing: "-0.02em",
              }}
            >
              {title}
            </span>

            {subtitle && (
              <span style={{ fontSize: 26, color: "#a8a8a8", lineHeight: 1.4 }}>
                {subtitle}
              </span>
            )}
          </div>
        </div>

        {/* Footer branding */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            width: "100%",
            zIndex: 1,
          }}
        >
          {/* Logo + name */}
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                width: 48,
                height: 48,
                background: brandPrimary,
                borderRadius: 12,
              }}
            >
              {/* TODO: Replace initials with actual logo if needed */}
              <span style={{ fontSize: 22, fontWeight: 700, color: "#ffffff" }}>
                {brandInitials}
              </span>
            </div>
            <span style={{ fontSize: 30, fontWeight: 700, color: "#ffffff" }}>
              {brandName}
            </span>
          </div>

          {/* URL pill */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              padding: "8px 20px",
              background: "rgba(255,255,255,0.05)",
              borderRadius: 20,
            }}
          >
            <span style={{ fontSize: 20, color: "#888888" }}>{brandUrl}</span>
          </div>
        </div>
      </div>
    ),
    { ...size }
  );
}
