// OG image component for blog articles.
// Called from: src/app/blog/<slug>/opengraph-image.tsx (generated by engine)
//
// Contract — engine calls it like this:
//   BlogOGImage({ title: "...", category: "Guide", subtitle: "optional subtitle" })
//
// Must return an ImageResponse (1200x630).
//
// TODO: Implement with your brand colors, logo, and typography.
//
// Example implementation:
//
// import { ImageResponse } from "next/og";
//
// export function BlogOGImage({ title, category, subtitle }: BlogOGImageProps) {
//   return new ImageResponse(
//     (
//       <div
//         style={{
//           width: "1200px",
//           height: "630px",
//           display: "flex",
//           flexDirection: "column",
//           justifyContent: "flex-end",
//           padding: "60px",
//           background: "linear-gradient(135deg, #0f0b1a 0%, #1d1535 100%)",
//         }}
//       >
//         <span style={{ color: "#a78bfa", fontSize: 20, marginBottom: 16 }}>
//           {category}
//         </span>
//         <h1 style={{ color: "#ede9f8", fontSize: 56, fontWeight: 700, lineHeight: 1.2, margin: 0 }}>
//           {title}
//         </h1>
//         {subtitle && (
//           <p style={{ color: "#9d8ec4", fontSize: 24, marginTop: 24 }}>{subtitle}</p>
//         )}
//       </div>
//     ),
//     { width: 1200, height: 630 }
//   );
// }

interface BlogOGImageProps {
  title: string;
  category: string;
  subtitle?: string;
}

// Placeholder — replace with real ImageResponse implementation
export function BlogOGImage({ title, category, subtitle }: BlogOGImageProps) {
  void title;
  void category;
  void subtitle;
  return null;
}
